#+TITLE: Логово
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org.css" />
#+HTML_HEAD: <style>div.figure img {max-height:300px;max-width:900px;}</style>
#+HTML_HEAD_EXTRA: <style>.org-src-container {background-color: #303030; color: #e5e5e5;}</style>

Ресурс, посвящённый олимпиадам и внешкольным математике и программированию в *Мелеузе*. (обновления страницы каждое воскресенье)\\
Заинтересованным писать в [[https://t.me/mlz_inc][Телегу]] (чат mlz-inc) или на почту jury.mlz.inc@gmail.com \\

* Анонсы 
  :PROPERTIES:
  :CUSTOM_ID: announce
  :END:

** Местный контест по программированию 16 или 17 мая 
+ Что будет: 5 задач на 2-3 часа. 
+ Кто может принимать участие: все желающие
+ Платформа: codeforces.com
+ Is it rated? No.
Остальная информация позже. По вопросам писать в группу вк / в беседу Телеги. 

* Цель создания логова 
  :PROPERTIES:
  :CUSTOM_ID: aim
  :END:
  Как известно, математического образования в Мелеузе *нет*. А значит, *нужно его создать*!\\
  \\
  Что до программирования, его основы даёт учитель 3-й гимназии. Однако его одного, очевидно, мало для всего города. Значит, *нужно помочь*!\\
  \\
  В наше время две эти области являются взаимодополняющими, поэтому продвигать их вместе является логичным.\\
  
** Как это осуществить?
   Олимпиадников в Мелеузе мало, все они сидят по своим домам, друг с другом не общаются из-за нехватки смелости / мыслей, что общение не так и важно / незнания о существовании других олимпиадников / иные причины. Можно попытаться изменить это, организовав ресурс, на котором будет "граф олимпиадной жизни" Мелеуза. Чтобы люди, заходившие сюда, находили нужные контакты и получали интересующую их информацию, причём не в школьном формате, когда вопросы задаются только учителям, а в через общение с такими же задротами (в хорошем смысле), как они. Впоследствии можно будет организовывать совместные покатушки на олимпиады / ботанье интересных тем / турниры по ЧГК.  \\
\\
Невероятно, но школьники сами способны обеспечить себе интересную учёбу при должной поддержке, сами могут организовать математический кружок, развивать свои задумки. Для этого достаточно смелости и желания познавать. 
 
* Первые шаги 
  :PROPERTIES:
  :CUSTOM_ID: steps
  :END:
  
  В ближайшие дни начну запрашивать разрешение известных мне олимпиадников для публикования их контактов, краткой информации о них на отдельной странце этого ресурса. Возможно сохранение анонимности, если кому-то нужно. Формат будет примерно таким (отдельно по предметам): \\ 
<Имя/ник человека> <опыт участия в олимпиадах> <темы, которые он хорошо знает> <темы, в которых интересуется> <контакты в телеге/где-то ещё> \\
\\
Чем больше будет собрано информации, тем интереснее! Потом можно будет визуализировать это для большей наглядности. \\ 
\\
Также прошу всех из Мелеуза, кто участвует в контестах на codeforces, указывать страну и город. Так будет интереснее соревноваться между собой.
* Затравка

  Никого не призываю осваивать эту жесть, но вот вам [[http://imperium.lenin.ru/~verbit/MATH/programma.html][программа Вербицкого]]. Она, конечно, рассчитана на тех, кто хочет сделать математику свой профессией, однако может являться бездонным кладезем тем для изучения. \\
  \\
  Кроме того, уверен, будет интересно посмотреть курсы [[https://www.mccme.ru/ium/][НМУ]], а также записи прошлых лет [[https://www.mccme.ru/dubna/][школы "Современная математика"]].

  
* ТИПО полезные ссылки:  
  :PROPERTIES:
  :CUSTOM_ID: links
  :END:
  - [[https://olimpiada.ru/][Olimpiada.ru]] - сайт со школьными олимпиадами и новостями по ним, а также [[https://info.olimpiada.ru/events][список]] ближайших олимпиад 
  - [[http://postypashki.ru/][Поступашки]] - ресурс, на котором расписано, зачем нужны олимпиады, что такое БВИ и как проводится устный этап ТурГора 
  - [[http://postypashki.ru/%d0%bb%d0%b8%d1%82%d0%b5%d1%80%d0%b0%d1%82%d1%83%d1%80%d0%b0/][Список]] полезной литературы и листков по математике с Поступашек
  - Платформа для соревнований по программированию [[https://codeforces.com/][codeforces.com]]
  - Новая платформа наподобие кодфорсеса - [[http://mathforces.com/][mathforces.com]]

  - [[file:acmp/real_table.org][Таблица]] *реального* рейтинга [[https://acmp.ru/][acmp.ru]] по Мелеузу (показаны только активные за последние 30 дней, обновляется 3 раза в день)  
  - Группы вк по олимппроге в Мелеузе [[https://vk.com/mlzinc][раз]], [[https://vk.com/olimpinf][два]].
  - [[https://github.com/mlz-inc/mlz-inc.github.io][GitHub-репозиторий]] этой страницы, в который каждый может вносить свои изменения (в случае полного доверия, напрямую)

* Начало 
  :PROPERTIES:
  :CUSTOM_ID: questions
  :END:
  Нужно определить, как сейчас обстоит дело с олимпиадами и в целом с уровнем матеши и проги в городе.\\

  Уже очень долгое время не поступает ответов. Чтож, придётся зарашить.

*** TODO Для того, чтобы преодолеть данный этап задаю вам (всем) вопросы:
  
1) Кто из учителей заинтересован в олимпиадах по математике и программированию, и действительно *может подготовить* школьников до уровня хотя бы призёра региона?
2) В каких школах есть *"заражённые"* этими предметами ученики? 
3) Как организовано *взаимодействие* между такими учениками? 
4) Как организовывается *проведение олимпиад* (школьный, муниципальный этапы), осведомление школьников о *перечневых олимпиадах* и о том, как они помогают при поступлении в вузы?
5) Есть ли в городе люди, которым действительно *интересно заниматься* такой организацией, а не просто выполнять предписанные обязательства?
6) Есть ли среди выпускников школ Мелеуза люди, занимающиеся *реальной математикой*? 
\\
Ответы будут выкладываться сюда по мере их поступления. Прошу всяческого содействия. 

(Telegram: mlz-inc или jury.mlz.inc@gmail.com)
