#+TITLE: Логово
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org.css" />
#+HTML_HEAD: <style>div.figure img {max-height:300px;max-width:900px;}</style>
#+HTML_HEAD_EXTRA: <style>.org-src-container {background-color: #303030; color: #e5e5e5;}</style>

Ресурс, посвящённый олимпиадам и внешкольным математике и программированию в *Мелеузе*.\\
\\
Сейчас карантин, соответственно, появилось больше времени на подумать. Поэтому выкатываю эту страницу.\\
/*В связи с переходом на дистанционное обучение после каникул, предлагаю разнообразить занятия, например, привлекая к проведению людей из других школ, или вообще не учителей.*/
\\
Заинтересованным писать в [[https://t.me/mlz_inc][Телегу]] (группа mlz-inc) или на почту jury.mlz.inc@gmail.com

* Начало 

  Нужно определить, как сейчас обстоит дело с олимпиадами и в целом с уровнем матеши и проги в городе.\\

*** TODO Для того, чтобы преодолеть данный этап задаю вам (всем) вопросы:
  
1) Кто из учителей заинтересован в олимпиадах по математике и программированию, и действительно *может подготовить* школьников до уровня хотя бы призёра региона?
2) В каких школах есть *"заражённые"* этими предметами ученики? 
3) Как организовано *взаимодействие* между такими учениками? 
4) Как организовывается *проведение олимпиад* (школьный, муниципальный этапы), осведомление школьников о *перечневых олимпиадах* и о том, как они помогают при поступлении в вузы?
5) Есть ли в городе люди, которым действительно *интересно заниматься* такой организацией, а не просто выполнять предписанные обязательства?
6) Есть ли среди выпускников школ Мелеуза люди, занимающиеся *реальной математикой*? 
\\
Ответы будут выкладываться сюда по мере их поступления. Прошу всяческого содействия. 

(Telegram: mlz-inc или jury.mlz.inc@gmail.com)

* Цель создания логова
  Как известно, математического образования в Мелеузе *нет*. А значит, *нужно его создать*!\\
  \\
  Что до программирования, его основы даёт учитель 3-й гимназии. Однако его одного, очевидно, мало для всего города. Значит, *нужно помочь*!\\
  \\
  В наше время две эти области являются взаимодополняющими, поэтому продвигать их вместе является логичным.\\
  
** Как это осуществить?
   Есть продуманные меры, но о них позже.
 
* Затравка

  Никого не призываю осваивать эту жесть, но вот вам [[http://imperium.lenin.ru/~verbit/MATH/programma.html][программа Вербицкого]]. Она, конечно, рассчитана на тех, кто хочет сделать математику свой профессией, однако может являться бездонным кладезем тем для изучения. 

  Кроме того, уверен, будет интересно посмотреть курсы [[https://www.mccme.ru/ium/][НМУ]], а также записи прошлых лет [[https://www.mccme.ru/dubna/][школы "Современная математика"]].

  И последнее на сегодня: завтра на [[https://codeforces.com/?locale=ru][codeforces]] пройдёт Div. 3 раунд. Участвуйте! 


* TODO ТИПО полезные ссылки:  
  - [[https://github.com/mlz-inc/mlz-inc.github.io][GitHub-репозиторий]] этой страницы, в который каждый может вносить свои изменения (в случае полного доверия, напрямую)
  - [[file:acmp/real_table.org][Таблица]] *реального* рейтинга acmp.ru по Мелеузу (активность за последние 30 дней)
  - [[file:old-paper.org][Давний текст]] про подготовку к олимпиадам по математике (шёл в комплекте с архивом книг)
