#+TITLE: STARTER KIT, математика
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org.css" />
#+HTML_HEAD: <style>div.figure img {max-height:300px;max-width:900px;}</style>
#+HTML_HEAD_EXTRA: <style>.org-src-container {background-color: #303030; color: #e5e5e5;}</style>


*** Текст писался в 2018 году. Может, кому-то будет полезно.
***** За самими книгами можете обращаться в группу Телеги

Представляю список книг, по которым не так давно занимался я 
(а по некоторым и продолжаю). Данный список не исчерпывающий,
но может быть поспособствует вашему математическому развитию.
Изучив их даже на том уровне, на котором изучил их я, вы будете 
способны по крайней мере стать призёром олимиады СПбГУ по математике.
\\
\\
---
Предполагается, что вы отлично владеете школьной программой 
---

- Для начала можно почитать теорию и порешать задачи из "Ленинградские 
математические кружки", "Как решают нестандартные задачи". Таким образом
будет заложена база. 

- Комбинаторику предлагаю изучать по одноимённой книге Виленкиных.
Много полезной информации и задач по алгебре и ТЧ (теория чисел)
содержится в книге Алфутовой и Устинова.

- Более сложные и интересные задачи с минимумом теории по этим двум
темам представлены в книге Прасолова. По своему опыту скажу: изучать
эту книгу самостоятельно - трудное (но увлекательное, признаю) занятие.

- Геометрию приятнее всего изучать по книге Понарина. Однако будет
крайне полезно смотреть задачи и по Прасолову.

И так, книга, которую я открыл для себя слишком поздно - 
"Сборник материалов выездных школ команды Москвы на ВСЕРОСС".
Задачи из неё ОФИГЕННЫ. Если вы решите все их, то вероятно 
станете призёром ВСЕРОССА!
\\ 
\\ 

В папке "Интересные":
- Я поместил книгу Акопяна по геометрии, так как по ней можно самостоятельно
изучать данный раздел. В прямом смысле самостоятельно: понимать, 
что подразумевает рисунок формулировать теоремы, доказывать их.
- В книге по криптографии есть глава, посвящённая подготовке к олимпиаде
и приводится интересная теория. Попробуйте порешать задачи из неё,
не пожалеете)
- "Задачи 57 школы" - просто посмотрите, что реально можно изучать
на уроках в школе.
- Книга по алгебре - простая, но полезная для понимания данного раздела  
- И так, "Доказательства из книги", в которой собраны одни из красивейших
доказательств! Не весь материал понятен старшим школьникам. 

Для подготовки к различным этапам Всероссийской олимпиады школьников (ВОШ)
предлагаю решать задачи из книг Агаханова. Также необходимо(!) решать
задачи последних лет http://olympiads.mccme.ru/vmo/ 

Для подготовки к различным перечневым олимпиадам нужно решать задачи
прошлых лет этих олимпиад и смотреть теорию по темам представленных
там задач.

\\ 
\\
- Как должна выглядеть математическая программа по М. С. Вербицкому:
http://imperium.lenin.ru/~verbit/MATH/programma.html
здесь много страшных названий, скрывающих за собой простые, красивые вещи.

- Список рекомендуемой литературы Малого Мехмата МГУ:
http://mmmf.msu.ru/books/
все книжки кликабельны, выводится краткое описание.

- Серия “Библиотека «Математическое просвещение»”:
https://www.mccme.ru/mmmf-lectures/books/#book-1
найдёте для себя много интересного!

- Сайт МЦНМО, суперсодержательный - есть ссылки на основные ресурсы:
http://www.mcnmo.ru
советую обследовать его вдоль и поперёк (!!!)

- Ближайшие олимпиады:
https://info.olimpiada.ru/events
там же можно посмотреть, какие олимпиады уже идут

- Ну и куда без Поступашек:
https://vk.com/postypashki
освещаются многие основные события олимпиадного мира, начать нужно
с чтения вводной статьи. 
\\
\\
[[file:index.org][На главную]]
